### ISSUE TITLE
OKU

### ISSUE THREAD

**Issue by IceDragon200** [IceDragon200/mt-yatm#6]
OKU is the in-game computer programming and emulation system

## TODO

* [ ] Can assemble 6502 source
* [ ] Can execute 6502 binary
* [ ] Additional in-game tools for debugging programs (more on that when we get to that milestone I guess)

* [ ] Determine if it's worth keeping the RISCV ISA
